export default {
  common: {
    search: 'بحث',
    total: 'المجموع',
    quantity: 'الكمية',
    price: 'السعر',
    add: 'إضافة',
    remove: 'إزالة',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    loading: 'جاري التحميل...',
    error: 'حدث خطأ',
    success: 'تم بنجاح',
  },
  pos: {
    title: 'نقطة البيع',
    cart: 'السلة',
    checkout: 'الدفع',
    payment: 'الدفع',
    receipt: 'الإيصال',
    inventory: 'المخزون',
    reports: 'التقارير',
    settings: 'الإعدادات',
    categories: {
      all: 'جميع الفئات',
      food: 'طعام ومشروبات',
      electronics: 'إلكترونيات',
      clothing: 'ملابس',
      other: 'أخرى',
    },
  },
  cart: {
    empty: 'السلة فارغة',
    addItems: 'أضف منتجات للبدء',
    subtotal: 'المجموع الفرعي',
    tax: 'الضريبة',
    total: 'المجموع الكلي',
    checkout: 'متابعة الدفع',
  },
  payment: {
    title: 'الدفع',
    methods: {
      cash: 'نقداً',
      card: 'بطاقة',
    },
    amount: 'المبلغ',
    change: 'الباقي',
    complete: 'إتمام الدفع',
  },
  receipt: {
    title: 'الإيصال',
    orderNumber: 'طلب رقم',
    date: 'التاريخ',
    items: 'المنتجات',
    print: 'طباعة الإيصال',
    email: 'إرسال الإيصال بالبريد',
  },
  inventory: {
    title: 'إدارة المخزون',
    addProduct: 'إضافة منتج',
    editProduct: 'تعديل منتج',
    lowStock: 'مخزون منخفض',
    outOfStock: 'نفذ من المخزون',
  },
};