export const Categories = [
  {
    id: 'school-supplies',
    name: 'School Supplies',
    icon: 'book',
    subcategories: [
      { id: 'notebooks', name: 'Notebooks & Journals' },
      { id: 'binders', name: 'Binders & Folders' },
      { id: 'backpacks', name: 'Backpacks & Bags' },
      { id: 'basic-supplies', name: 'Basic Supplies' },
    ],
  },
  {
    id: 'writing-tools',
    name: 'Writing Tools',
    icon: 'pen-tool',
    subcategories: [
      { id: 'pens', name: 'Pens' },
      { id: 'pencils', name: 'Pencils' },
      { id: 'markers', name: 'Markers & Highlighters' },
      { id: 'erasers', name: 'Erasers & Correction' },
    ],
  },
  {
    id: 'art-supplies',
    name: 'Art Supplies',
    icon: 'palette',
    subcategories: [
      { id: 'paints', name: 'Paints & Brushes' },
      { id: 'drawing', name: 'Drawing Supplies' },
      { id: 'crafts', name: 'Craft Materials' },
      { id: 'paper', name: 'Art Paper & Canvases' },
    ],
  },
  {
    id: 'office-equipment',
    name: 'Office Equipment',
    icon: 'briefcase',
    subcategories: [
      { id: 'organization', name: 'Organization' },
      { id: 'desk-accessories', name: 'Desk Accessories' },
      { id: 'electronics', name: 'Office Electronics' },
      { id: 'papers', name: 'Papers & Forms' },
    ],
  },
];

export const Products = [
  // School Supplies - Notebooks & Journals
  {
    id: 'notebook-college-ruled',
    name: 'College Ruled Notebook',
    category: 'school-supplies',
    subcategory: 'notebooks',
    price: 4.99,
    discountPrice: 3.99,
    description: 'College ruled notebook with 70 sheets. Perfect for taking notes in class or at work.',
    features: ['College ruled', '70 sheets', 'Perforated pages', 'Three-hole punched'],
    image: 'https://images.pexels.com/photos/6053/notebook-laptop-pen-work.jpg?auto=compress&cs=tinysrgb&w=600',
    stock: 120,
    rating: 4.5,
    reviews: 28,
    isNew: false,
    isBestseller: true,
  },
  {
    id: 'journal-leather',
    name: 'Leather Bound Journal',
    category: 'school-supplies',
    subcategory: 'notebooks',
    price: 24.99,
    discountPrice: null,
    description: 'Handcrafted leather journal with 240 pages of premium paper. Includes a bookmark ribbon and elastic closure.',
    features: ['Genuine leather', '240 pages', 'Acid-free paper', 'Elastic closure', 'Bookmark ribbon'],
    image: 'https://images.pexels.com/photos/262034/pexels-photo-262034.jpeg?auto=compress&cs=tinysrgb&w=600',
    stock: 45,
    rating: 4.8,
    reviews: 156,
    isNew: false,
    isBestseller: true,
  },
  
  // Writing Tools - Pens
  {
    id: 'pen-gel-10pack',
    name: 'Gel Pens Set (10-Pack)',
    category: 'writing-tools',
    subcategory: 'pens',
    price: 12.99,
    discountPrice: 9.99,
    description: 'Set of 10 smooth-writing gel pens in assorted colors. Quick-drying ink prevents smudging.',
    features: ['10 assorted colors', 'Quick-drying gel ink', '0.7mm medium point', 'Comfortable grip'],
    image: 'https://images.pexels.com/photos/207665/pexels-photo-207665.jpeg?auto=compress&cs=tinysrgb&w=600',
    stock: 230,
    rating: 4.6,
    reviews: 89,
    isNew: false,
    isBestseller: true,
  },
  {
    id: 'pen-fountain',
    name: 'Premium Fountain Pen',
    category: 'writing-tools',
    subcategory: 'pens',
    price: 35.99,
    discountPrice: null,
    description: 'Elegant fountain pen with a stainless steel nib and refillable ink cartridge. Comes in a gift box.',
    features: ['Stainless steel nib', 'Refillable ink cartridge', 'Balanced weight', 'Gift box included'],
    image: 'https://images.pexels.com/photos/163186/typewriter-vintage-old-vintage-typewriter-163186.jpeg?auto=compress&cs=tinysrgb&w=600',
    stock: 60,
    rating: 4.9,
    reviews: 42,
    isNew: true,
    isBestseller: false,
  },
  
  // Art Supplies - Paints & Brushes
  {
    id: 'paint-acrylic-set',
    name: 'Acrylic Paint Set (12 Colors)',
    category: 'art-supplies',
    subcategory: 'paints',
    price: 29.99,
    discountPrice: 24.99,
    description: 'Set of 12 vibrant acrylic paints for artists of all levels. Highly pigmented and quick-drying.',
    features: ['12 vibrant colors', 'Highly pigmented', 'Quick-drying', 'Non-toxic'],
    image: 'https://images.pexels.com/photos/1047540/pexels-photo-1047540.jpeg?auto=compress&cs=tinysrgb&w=600',
    stock: 85,
    rating: 4.7,
    reviews: 63,
    isNew: false,
    isBestseller: false,
  },
  {
    id: 'brush-set-professional',
    name: 'Professional Paint Brush Set',
    category: 'art-supplies',
    subcategory: 'paints',
    price: 34.99,
    discountPrice: null,
    description: 'Set of 15 professional-grade brushes for watercolor, acrylic, and oil painting. Various shapes and sizes included.',
    features: ['15 brushes in various sizes', 'Natural and synthetic bristles', 'Wooden handles', 'Portable case included'],
    image: 'https://images.pexels.com/photos/1327716/pexels-photo-1327716.jpeg?auto=compress&cs=tinysrgb&w=600',
    stock: 70,
    rating: 4.8,
    reviews: 37,
    isNew: true,
    isBestseller: false,
  },
  
  // Office Equipment - Desk Accessories
  {
    id: 'desk-organizer',
    name: 'Multi-Compartment Desk Organizer',
    category: 'office-equipment',
    subcategory: 'desk-accessories',
    price: 19.99,
    discountPrice: 16.99,
    description: 'Keep your workspace tidy with this multi-compartment desk organizer. Perfect for storing pens, sticky notes, paper clips, and more.',
    features: ['Multiple compartments', 'Durable construction', 'Space-saving design', 'Non-slip base'],
    image: 'https://images.pexels.com/photos/3932964/pexels-photo-3932964.jpeg?auto=compress&cs=tinysrgb&w=600',
    stock: 110,
    rating: 4.4,
    reviews: 52,
    isNew: false,
    isBestseller: false,
  },
  {
    id: 'stapler-premium',
    name: 'Premium Desktop Stapler',
    category: 'office-equipment',
    subcategory: 'desk-accessories',
    price: 14.99,
    discountPrice: null,
    description: 'Heavy-duty desktop stapler that can staple up to 20 sheets at once. Includes 1000 staples.',
    features: ['Staples up to 20 sheets', 'Durable metal construction', 'Non-slip base', 'Includes 1000 staples'],
    image: 'https://images.pexels.com/photos/4792729/pexels-photo-4792729.jpeg?auto=compress&cs=tinysrgb&w=600',
    stock: 95,
    rating: 4.3,
    reviews: 27,
    isNew: false,
    isBestseller: false,
  },
  
  // Additional products for various categories
  {
    id: 'backpack-student',
    name: 'Student Backpack with Laptop Compartment',
    category: 'school-supplies',
    subcategory: 'backpacks',
    price: 49.99,
    discountPrice: 39.99,
    description: 'Durable backpack with padded laptop compartment, multiple pockets, and comfortable straps. Perfect for students.',
    features: ['Padded laptop compartment (fits up to 15.6")', 'Multiple storage pockets', 'Water-resistant material', 'Padded back and straps'],
    image: 'https://images.pexels.com/photos/1546003/pexels-photo-1546003.jpeg?auto=compress&cs=tinysrgb&w=600',
    stock: 65,
    rating: 4.7,
    reviews: 118,
    isNew: false,
    isBestseller: true,
  },
  {
    id: 'pencil-mechanical-set',
    name: 'Mechanical Pencil Set (5-Pack)',
    category: 'writing-tools',
    subcategory: 'pencils',
    price: 14.99,
    discountPrice: 11.99,
    description: 'Set of 5 mechanical pencils with 0.5mm lead. Includes extra lead refills and erasers.',
    features: ['0.5mm lead', 'Comfortable grip', 'Includes refills and erasers', 'Click advancement mechanism'],
    image: 'https://images.pexels.com/photos/6475046/pexels-photo-6475046.jpeg?auto=compress&cs=tinysrgb&w=600',
    stock: 140,
    rating: 4.5,
    reviews: 74,
    isNew: false,
    isBestseller: false,
  },
  {
    id: 'sketchbook-artist',
    name: 'Artist Sketchbook (100 Sheets)',
    category: 'art-supplies',
    subcategory: 'paper',
    price: 19.99,
    discountPrice: null,
    description: 'High-quality sketchbook with 100 sheets of acid-free paper. Perfect for drawing, sketching, and mixed media.',
    features: ['100 sheets (200 pages)', 'Acid-free paper', 'Hardcover binding', 'Perforated pages for easy removal'],
    image: 'https://images.pexels.com/photos/733852/pexels-photo-733852.jpeg?auto=compress&cs=tinysrgb&w=600',
    stock: 90,
    rating: 4.8,
    reviews: 46,
    isNew: true,
    isBestseller: false,
  },
  {
    id: 'file-organizer',
    name: 'Expandable File Organizer',
    category: 'office-equipment',
    subcategory: 'organization',
    price: 22.99,
    discountPrice: 18.99,
    description: 'Expandable file organizer with 13 pockets for storing and organizing important documents. Includes labels.',
    features: ['13 expandable pockets', 'Durable construction', 'Includes labels', 'Secure elastic closure'],
    image: 'https://images.pexels.com/photos/6368663/pexels-photo-6368663.jpeg?auto=compress&cs=tinysrgb&w=600',
    stock: 75,
    rating: 4.4,
    reviews: 32,
    isNew: false,
    isBestseller: false,
  },
];