export default {
  common: {
    search: 'Search',
    total: 'Total',
    quantity: 'Quantity',
    price: 'Price',
    add: 'Add',
    remove: 'Remove',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success',
  },
  pos: {
    title: 'Point of Sale',
    cart: 'Cart',
    checkout: 'Checkout',
    payment: 'Payment',
    receipt: 'Receipt',
    inventory: 'Inventory',
    reports: 'Reports',
    settings: 'Settings',
    categories: {
      all: 'All Categories',
      food: 'Food & Beverages',
      electronics: 'Electronics',
      clothing: 'Clothing',
      other: 'Other',
    },
  },
  cart: {
    empty: 'Your cart is empty',
    addItems: 'Add items to get started',
    subtotal: 'Subtotal',
    tax: 'Tax',
    total: 'Total',
    checkout: 'Proceed to Checkout',
  },
  payment: {
    title: 'Payment',
    methods: {
      cash: 'Cash',
      card: 'Card',
    },
    amount: 'Amount',
    change: 'Change',
    complete: 'Complete Payment',
  },
  receipt: {
    title: 'Receipt',
    orderNumber: 'Order #',
    date: 'Date',
    items: 'Items',
    print: 'Print Receipt',
    email: 'Email Receipt',
  },
  inventory: {
    title: 'Inventory Management',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
  },
};